# Site settings
title: SuleymanFatihSimsek
author: SuleymanFatihSimsek
keywords: "programming, web Developer, JavaScript, Ruby"
description: "Linux Gelistiricisi,YKS ogrencisi"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suleymanfatih.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Social Links
email:             sp.samu152@hotmail.com
#google.plus:        username
twitter:            dogmasavar
facebook:           suleymanfatih.simsek
github:             suleymanfatih
# stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           süleyman-fatih-şimşek-bba9101bb
#xing:              username
instagram:          dogmasavar
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
youtube:           channel/UC65kqGSegAao8loePFUxDuQ
soundcloud:        suleymanfatih
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

timezone: "Europe/Istanbul"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

